#General config options
general:
  broadcast-ban: true
  broadcast-kick: true
  use-motd: true
  use-welcome-message: true
  show-location-message: true
  old-tnt: false

#Enable GUI Here!!!!
gui:
  enabled: false

#Item command options
item:
  default-stack-size: 64
  drop-extra-items: true

chat:
  format: '&7[{name}&7]: &f{msg}'

geoip:
  download-if-missing: true
  download-url: 'http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz'

#Misc. messages
messages:
  default-ban-message: '&7The Banhammer has spoken!'
  default-kick-message: '&7You have been kicked!'
  welcome-message: '&3Welcome {name} to {world}!'

#Disconnect messages for when a player is kicked/denied on login
disconnect-messages:
  banned: '&7You are banned from this server!'
  whitelist: '&6You are not on the whitelist!'
  full: '&6The server is currently full, try again later!'

#MOTD
# You may use the following variables
#{name} Players name
#{dispname} Players display name
#{online-count} Users online
#{world} The world the player is in
motd:
- '&6Welcome back {dispname}, You are in {world}!'
- '&6There are currently {online-count} players online.'
